import type { Metadata } from "next";
import { Jost } from "next/font/google";

import { SideBarCom } from "@/components";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financial",
  description: "Generated by LEGACYFA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={jost.className}>
        <div className="flex h-screen">
          <SideBarCom />
          <main className="flex-1 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
