import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Script from "next/script";

import { HeaderCom, SideBarCom } from "@/components";
import { Providers } from "./provider";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financial",
  description: "Generated by LEGACYFA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <Script
          src="https://unpkg.com/react/umd/react.production.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://unpkg.com/recharts/umd/Recharts.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={jost.className}>
        <Providers>
          <div className="flex h-screen">
            <SideBarCom />
            <div className="flex-1 flex flex-col">
              <HeaderCom />
              <main className="flex-1 overflow-y-auto p-4">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
